# Generated by Django 4.2.8 on 2024-02-14 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0009_alter_area_latitude_alter_area_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('WRONG_INFO', 'Неправильная информация'), ('CLOSED', 'Площадка закрылась'), ('CHANGE_COORDS', 'Уточнить местоположение'), ('OTHER', 'Другое')], max_length=20)),
                ('wrong_info', models.TextField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(upload_to='area_images/', verbose_name='изображение')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Долгота')),
                ('other_info', models.TextField(blank=True, max_length=256, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
