# Generated by Django 4.2.8 on 2024-02-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'уточнение информации', 'verbose_name_plural': 'уточнение информации'},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='image',
            new_name='images',
        ),
    ]
