# Generated by Django 4.2.8 on 2024-02-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_options_rename_image_report_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Долгота'),
        ),
    ]
