# Generated by Django 4.2.8 on 2024-02-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_latitude_alter_report_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='area',
        ),
    ]
