# Generated by Django 4.2.8 on 2024-01-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='categories',
            field=models.ManyToManyField(related_name='areas', to='areas.category', verbose_name='категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='уникальный тег'),
        ),
    ]
