# Generated by Django 4.2.8 on 2024-02-02 07:38

import django.core.validators
from django.db import migrations, models

import areas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2), areas.validators.validate_category_name], verbose_name='название'),
        ),
    ]
