# Generated by Django 4.2.8 on 2024-02-05 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('areas', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
    ]
