# Generated by Django 4.2.8 on 2024-02-06 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('areas', '0005_alter_area_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='areas.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранная площадка',
                'verbose_name_plural': 'Избранные площадки',
            },
        ),
        migrations.AddConstraint(
            model_name='favoritearea',
            constraint=models.UniqueConstraint(fields=('user', 'area'), name='unique_favorite_area'),
        ),
    ]
