# Generated by Django 4.2.8 on 2024-02-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0006_category_area_name_favoritearea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Описание площадки'),
        ),
    ]
