# Generated by Django 4.2.8 on 2024-02-08 19:45

import django.core.validators
from django.db import migrations, models

import areas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0007_area_address_area_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3), areas.validators.validate_category_name], verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=2000, verbose_name='комментарий'),
        ),
    ]
