# Generated by Django 4.2.8 on 2024-02-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0008_alter_category_name_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='area',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Долгота'),
        ),
    ]
