# Generated by Django 4.2.8 on 2024-02-02 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.SlugField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='никнейм'),
        ),
    ]
